### ISSUE TITLE
Failed to instantiate module!

### ISSUE THREAD

**Issue by oikonomopo** [tolyo/ionic-brunch-es6-seed#2]
When run tha app _...Module 'app.playlists' is not available!..._

1. ```git clone git@github.com:tolyo/ionic-brunch-es6-seed.git```
2. ```cd ionic-brunch-es6-seed```
3. ```npm install```
-------------------------------------------------------------------
_Using ionic-cli 3.3.0, needs a rename to the following file._
4 _Rename_ `ionic.project` to `ionic.config.json` and add ionic version type:
```
{
  "name": "ionic-brunch-es6-seed",
  "app_id": "",
  "type": "ionic1"
}
```
5. Running the app during development with either `npm run mobile` to serve using Brunch or `npm run desktop` to serve using Electron, app starts blank and i have the following error:
```
Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module app.playlists due to:
Error: [$injector:nomod] Module 'app.playlists' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.6.4/$injector/nomod?p0=app.playlists
    at file:///Users/oikonomopo/Projects/ionic-brunch-es6-seed/www/js/app.js:9849:12
    at file:///Users/oikonomopo/Projects/ionic-brunch-es6-seed/www/js/app.js:12045:17
    at ensure (file:///Users/oikonomopo/Projects/ionic-brunch-es6-seed/www/js/app.js:11966:38)
    at module (file:///Users/oikonomopo/Projects/ionic-brunch-es6-seed/www/js/app.js:12043:14)
    at file:///Users/oikonomopo/Projects/ionic-brunch-es6-seed/www/js/app.js:14679:22
    at forEach (file:///Users/oikonomopo/Projects/ionic-brunch-es6-seed/www/js/app.js:10186:20)
    at loadModules (file:///Users/oikonomopo/Projects/ionic-brunch-es6-seed/www/js/app.js:14663:5)
    at file:///Users/oikonomopo/Projects/ionic-brunch-es6-seed/www/js/app.js:14681:40
    at forEach (file:///Users/oikonomopo/Projects/ionic-brunch-es6-seed/www/js/app.js:10186:20)
    at loadModules (file:///Users/oikonomopo/Projects/ionic-brunch-es6-seed/www/js/app.js:14663:5)
http://errors.angularjs.org/1.6.4/$injector/modulerr?p0=app.playlists&p1=Er…onomopo%2FProjects%2Fionic-brunch-es6-seed%2Fwww%2Fjs%2Fapp.js%3A14663%3A5)
    at file:///Users/oikonomopo/Projects/ionic-brunch-es6-seed/www/js/app.js:9849:12
    at file:///Users/oikonomopo/Projects/ionic-brunch-es6-seed/www/js/app.js:14703:15
    at forEach (file:///Users/oikonomopo/Projects/ionic-brunch-es6-seed/www/js/app.js:10186:20)
    at loadModules (file:///Users/oikonomopo/Projects/ionic-brunch-es6-seed/www/js/app.js:14663:5)
    at file:///Users/oikonomopo/Projects/ionic-brunch-es6-seed/www/js/app.js:14681:40
    at forEach (file:///Users/oikonomopo/Projects/ionic-brunch-es6-seed/www/js/app.js:10186:20)
    at loadModules (file:///Users/oikonomopo/Projects/ionic-brunch-es6-seed/www/js/app.js:14663:5)
    at createInjector (file:///Users/oikonomopo/Projects/ionic-brunch-es6-seed/www/js/app.js:14585:19)
    at doBootstrap (file:///Users/oikonomopo/Projects/ionic-brunch-es6-seed/www/js/app.js:11697:20)
    at bootstrap (file:///Users/oikonomopo/Projects/ionic-brunch-es6-seed/www/js/app.js:11718:12)
http://errors.angularjs.org/1.6.4/$injector/modulerr?p0=app&p1=Error%3A%20%…nomopo%2FProjects%2Fionic-brunch-es6-seed%2Fwww%2Fjs%2Fapp.js%3A11718%3A12)(anonymous function) @ angular.js:70(anonymous function) @ angular.js:4924forEach @ angular.js:407loadModules @ angular.js:4884createInjector @ angular.js:4806doBootstrap @ angular.js:1918bootstrap @ angular.js:1939angularInit @ angular.js:1824(anonymous function) @ angular.js:33371trigger @ angular.js:3435
```

**Comment by tolyo** [comment]
Please try making any change in `app.js` to trigger a recompile. I have noticed this problem sometimes occurring during initial install, but it is not unique to this particular project.

**Comment by andplusblaw** [comment]
Sorry, but I am getting the same issue and I have tried editing the app.js to trigger a recompile.

**Comment by tolyo** [comment]
Try the latest patches please.
